<?php

namespace Tests\Feature;

use App\Models\Project;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Support\Arr;
use Tests\TestCase;

class ProjectTest extends TestCase
{
    use WithFaker;
    use RefreshDatabase;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }


    public function test_only_authenticate_user_can_create_project()
    {
        $data = Project::factory()->raw();
        $this->post('projects', $data)
            ->assertRedirect(route('login'));
    }

    /**
     * A basic feature test example.
     *
     * @return void
     */
    public function test_user_can_create_a_project()
    {
        $this->withoutExceptionHandling();
        $data = [
            'title' => $this->faker->sentence,
            'description' => $this->faker->paragraph,
        ];
        $this->actingAs(User::factory()->create())->post('projects', $data)
            ->assertRedirect(route('projects.index'));

        $this->assertDatabaseHas('projects', $data);

        $this->get('projects')->assertSee($data);

    }

    public function test_project_required_a_title()
    {
        $data = Project::factory()->raw(['title' => null]);
        $this->actingAs(User::factory()->create())->post('projects', $data)
            ->assertSessionHasErrors(['title']);
    }

    public function test_a_user_can_view_project()
    {
        $project = Project::factory()->create();

        $this->get(route('projects.show', $project->id))
            ->assertSee(Arr::only($project->getAttributes(), ['title', 'description']));
    }
}
